[package]
name = "rakka-example-sharded-cart-persistence"
version = "0.1.0"
description.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
license-file.workspace = true
publish = false

[dependencies]
rakka = { path = "../../crates/rakka", default-features = false, features = ["persistence", "sharding"] }
tokio.workspace = true

[lints]
workspace = true
