[package]
name = "rakka-process"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true

[dependencies]
rakka-core = { path = "../rakka-core" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
