[package]
name = "rakka-remote"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true

[dependencies]
prost.workspace = true
rakka-cluster = { path = "../rakka-cluster" }
rakka-core = { path = "../rakka-core" }
serde.workspace = true
tokio.workspace = true

[lints]
workspace = true
