[package]
name = "rakka-stream"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true

[dependencies]
rakka-core = { path = "../rakka-core" }
rakka-process = { path = "../rakka-process" }
rakka-sharding = { path = "../rakka-sharding" }
tokio.workspace = true

[dev-dependencies]
rakka-cluster = { path = "../rakka-cluster" }

[lints]
workspace = true
