[package]
name = "rakka-example-minimal-system"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
publish = false

[dependencies]
rakka-core = { path = "../../crates/rakka-core" }
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
