[package]
name = "rakka-persistence-postgres"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true

[dependencies]
rakka-core = { path = "../rakka-core" }
rakka-persistence = { path = "../rakka-persistence" }
tokio-postgres.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
