[package]
name = "rakka-sharding"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true

[lib]
name = "rakka_sharding"

[dependencies]
rakka-cluster = { path = "../rakka-cluster" }
rakka-core = { path = "../rakka-core" }
rakka-remote = { path = "../rakka-remote" }
serde.workspace = true
tokio.workspace = true

[dev-dependencies]
prost.workspace = true

[lints]
workspace = true
