[package]
name = "rakka-example-coordinated-shutdown"
version = "0.1.0"
description.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
license-file.workspace = true
publish = false

[[bin]]
name = "rakka-example-coordinated-shutdown"
path = "src/main.rs"
doc = false

[dependencies]
rakka = { path = "../../crates/rakka" }
tokio.workspace = true

[lints]
workspace = true
